'use strict';
const $=id=>document.getElementById(id);
const STORE='fairytale-local-v1';
const state={project:null,step:1,key:sessionStorage.getItem('fairytale-gemini-key')||'',files:new Map(),busy:false};
const el=(tag,cls='',text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
function notice(text,bad=false){$('notice').textContent=text;$('notice').className='notice'+(bad?' error':'');}
function clearNotice(){$('notice').className='notice hidden';$('notice').textContent='';}
function save(){try{localStorage.setItem(STORE,JSON.stringify({project:state.project,step:state.step,draft:{title:$('title').value,story:$('story').value,cuts:$('cuts').value}}));}catch{notice('브라우저 저장 공간이 부족합니다. 프롬프트를 복사해 보관해 주세요.',true);}}
function step(n){if(n>1&&!state.project?.scenes?.length){notice('먼저 프롬프트를 생성해 주세요.',true);return;}state.step=n;for(let i=1;i<=3;i++)$('step'+i).classList.toggle('hidden',i!==n);document.querySelectorAll('.step').forEach(x=>{let yes=Number(x.dataset.step)===n;x.classList.toggle('active',yes);x.setAttribute('aria-current',yes?'step':'false');});if(n===3)uploads();save();window.scrollTo({top:0,behavior:'smooth'});}
function edit(parent,label,value,update){const box=el('div'),row=el('div','field-heading'),area=el('textarea','prompt-text');row.append(el('label','',label));area.value=value||'';area.setAttribute('aria-label',label);area.addEventListener('input',()=>{update(area.value);save();});const b=el('button','copy','복사');b.type='button';b.onclick=async()=>{try{await navigator.clipboard.writeText(area.value);b.textContent='복사됨 ✓';setTimeout(()=>b.textContent='복사',1200);}catch{notice('텍스트를 길게 눌러 복사해 주세요.',true);}};row.append(b);box.append(row,area);parent.append(box);}
function prompts(){const p=state.project;if(!p)return;$('countLabel').textContent=p.cuts+'컷';$('characters').replaceChildren();$('prompts').replaceChildren();p.characters.forEach((c,i)=>{const card=el('article','card');card.append(el('h4','',c.name||'캐릭터 '+(i+1)));edit(card,'캐릭터 이미지 프롬프트',c.prompt,v=>c.prompt=v);$('characters').append(card);});p.scenes.forEach((s,i)=>{const card=el('article','card');card.append(el('h4','','컷 '+(i+1)+' · '+s.title));edit(card,'장면 이미지 프롬프트',s.imagePrompt,v=>s.imagePrompt=v);edit(card,'Google Veo 영상 프롬프트',s.veoPrompt,v=>s.veoPrompt=v);edit(card,'한국어 나레이션 대본 (참고용)',s.narration,v=>s.narration=v);$('prompts').append(card);});}
const schema={type:'OBJECT',properties:{characters:{type:'ARRAY',items:{type:'OBJECT',properties:{name:{type:'STRING'},prompt:{type:'STRING'}},required:['name','prompt']}},scenes:{type:'ARRAY',items:{type:'OBJECT',properties:{title:{type:'STRING'},imagePrompt:{type:'STRING'},veoPrompt:{type:'STRING'},narration:{type:'STRING'}},required:['title','imagePrompt','veoPrompt','narration']}}},required:['characters','scenes']};
const AUDIO='No dialogue, no speech, no voice-over, no singing, no vocals, no lip-sync. Only instrumental background music, ambience and natural sound effects.';
const VISUAL='No on-screen text, captions, titles, logos, readable signs or watermarks.';
async function generate(e){e.preventDefault();if(state.busy)return;const title=$('title').value.trim(),story=$('story').value.trim(),cuts=Number($('cuts').value);if(!title||!story||!Number.isInteger(cuts)||cuts<1||cuts>10)return;if(!state.key){$('connect').click();notice('먼저 Gemini API 키를 설정해 주세요.',true);return;}
state.busy=true;$('generate').disabled=true;$('generate').textContent='Gemini 프롬프트 생성 중…';notice('Google Gemini에 이야기를 전송해 장면을 구성하고 있습니다.');
try{const prompt=`Create exactly ${cuts} scenes for a warm Korean bedtime fairy-tale video. Keep all key plot events and the original ending. For each main character write a detailed consistent English image reference prompt. For each scene write a complete independent English 9:16 image prompt and a detailed 10-second Google Veo video prompt with character consistency, action, camera, lighting, animation style and ONLY instrumental background music and ambience. No dialogue, speech or text in videos. Include a short Korean narration script for future reference, but do not put narration in Veo prompts. Title: ${title}\nStory: ${story}`;
const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':state.key},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json',responseSchema:schema,maxOutputTokens:16384,temperature:0.6}})});
const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error?.message||'Google API 오류 HTTP '+r.status);const raw=j.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('');if(!raw)throw Error('Gemini 응답이 비어 있습니다.');const data=JSON.parse(raw);if(!Array.isArray(data.scenes)||data.scenes.length!==cuts||!Array.isArray(data.characters))throw Error('Gemini가 요청한 컷수를 반환하지 않았습니다.');
data.scenes.forEach(s=>s.veoPrompt+='\n'+AUDIO+'\n'+VISUAL);state.files.clear();state.project={id:crypto.randomUUID(),title,story,cuts,...data};save();prompts();clearNotice();step(2);
}catch(err){notice('프롬프트 생성 실패: '+err.message,true);}finally{state.busy=false;$('generate').disabled=false;$('generate').textContent='AI 프롬프트 생성 →';}}
function uploads(){const p=state.project;if(!p)return;const n=state.files.size;$('uploadSummary').textContent='영상 선택: '+n+' / '+p.cuts+'컷';$('meterFill').style.width=100*n/p.cuts+'%';$('render').disabled=n!==p.cuts||state.busy;$('render').textContent=n===p.cuts?'내 기기에서 영상 합치기 →':'모든 컷을 선택해 주세요';$('uploads').replaceChildren();
p.scenes.forEach((s,i)=>{const file=state.files.get(i),card=el('article','card upload-card'),row=el('div','file-row'),player=el('video',file?'':'hidden'),input=el('input');row.append(el('h4','','컷 '+(i+1)+' · '+s.title),el('span','badge'+(file?' ready':''),file?'영상 준비 완료':'영상 없음'));card.append(row,el('p','',file?file.name:'기기에서 MP4 파일을 선택하세요.'));player.controls=true;player.playsInline=true;if(file){player.src=URL.createObjectURL(file);player.onloadeddata=()=>URL.revokeObjectURL(player.src);}card.append(player);input.type='file';input.accept='video/mp4,.mp4';input.setAttribute('aria-label','컷 '+(i+1)+' MP4 선택');input.onchange=()=>{if(!input.files?.[0])return;const f=input.files[0];if(!/\.mp4$/i.test(f.name)){notice('MP4 파일을 선택해 주세요.',true);return;}state.files.set(i,f);uploads();};card.append(input);$('uploads').append(card);});}
async function loadFFmpeg(){if(window.FFmpegWASM?.FFmpeg)return;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=new URL('ffmpeg/ffmpeg.js',document.baseURI).href;s.onload=()=>window.FFmpegWASM?.FFmpeg?resolve():reject(Error('FFmpeg 라이브러리 초기화 실패'));s.onerror=()=>reject(Error('FFmpeg 라이브러리 다운로드 실패'));document.head.append(s);});}
async function render(){const p=state.project;if(!p||state.files.size!==p.cuts||state.busy)return;state.busy=true;uploads();const box=$('renderStatus');box.className='status';box.textContent='영상 합성 도구를 불러오는 중입니다. 모바일에서는 메모리 부족으로 실패할 수 있습니다.';let ff,stage='라이브러리 다운로드';
try{await loadFFmpeg();stage='FFmpeg 객체 생성';ff=new FFmpegWASM.FFmpeg();ff.on('log',({message})=>{if(/time=/.test(message))box.textContent='영상 합성 중… '+message.slice(-100);});stage='FFmpeg 엔진 다운로드';const base=new URL('ffmpeg/',document.baseURI);const coreURL=new URL('ffmpeg-core.js',base).href,wasmURL=new URL('ffmpeg-core.wasm',base).href,workerURL=new URL('worker.js',base).href;stage='FFmpeg 엔진 초기화';box.textContent='영상 합성 엔진 초기화 중…';await ff.load({coreURL,wasmURL,classWorkerURL:workerURL});
stage='영상 파일 준비';let lines=[];for(let i=0;i<p.cuts;i++){box.textContent='컷 '+(i+1)+' / '+p.cuts+' 준비 중…';const f=state.files.get(i);await ff.writeFile('cut'+i+'.mp4',new Uint8Array(await f.arrayBuffer()));lines.push("file 'cut"+i+".mp4'");}await ff.writeFile('list.txt',new TextEncoder().encode(lines.join('\n')));box.textContent='컷들을 MP4로 합치는 중입니다…';stage='MP4 병합';const rc=await ff.exec(['-f','concat','-safe','0','-i','list.txt','-c','copy','-movflags','+faststart','finished.mp4']);if(rc!==0)throw Error('영상의 코덱이나 해상도가 서로 다를 수 있습니다. 동일한 Veo 설정의 MP4를 사용해 주세요.');stage='MP4 결과 읽기';const data=await ff.readFile('finished.mp4');if(data.byteLength<1000)throw Error('완성 영상이 비어 있습니다.');const url=URL.createObjectURL(new Blob([data],{type:'video/mp4'}));box.replaceChildren(el('strong','','MP4 완성! 원본 영상의 배경음이 유지됩니다.'));const a=el('a','primary','완성 MP4 다운로드');a.href=url;a.download=(p.title||'fairytale').replace(/[\\\\/:*?"<>|]/g,'_')+'.mp4';a.style.display='inline-block';a.style.marginTop='12px';box.append(el('br'),a);notice('서버 업로드 없이 기기에서 영상 합성을 완료했습니다.');
}catch(err){box.className='status error';box.textContent='영상 합성 실패 ['+stage+']: '+(err?.message||String(err)||'브라우저에서 오류 세부 내용을 제공하지 않았습니다.')+' · 영상은 삭제되지 않았습니다. 모바일에서 엔진 초기화가 실패하면 PC Chrome을 이용해 주세요.';}finally{if(ff)try{ff.terminate();}catch{}state.busy=false;uploads();}}
function init(){for(let i=1;i<=10;i++){const o=el('option','',i+'컷');o.value=i;$('cuts').append(o);}$('cuts').value='8';try{const d=JSON.parse(localStorage.getItem(STORE)||'null');if(d){const draft=d.draft||{};$('title').value=draft.title||'';$('story').value=draft.story||'';$('cuts').value=draft.cuts||8;if(d.project?.scenes?.length){state.project=d.project;prompts();step(d.step===3?2:d.step||1);}}}catch{localStorage.removeItem(STORE);}
for(const id of ['title','story','cuts'])$(id).addEventListener('input',save);document.querySelectorAll('.step').forEach(b=>b.onclick=()=>step(Number(b.dataset.step)));$('storyForm').onsubmit=generate;$('back1').onclick=()=>step(1);$('back2').onclick=()=>step(2);$('next3').onclick=()=>step(3);$('render').onclick=render;
$('new').onclick=()=>{if(state.busy)return;if(!confirm('새 동화를 시작할까요? 현재 입력과 프롬프트가 초기화됩니다.'))return;state.project=null;state.files.clear();localStorage.removeItem(STORE);$('title').value='';$('story').value='';$('cuts').value='8';$('renderStatus').className='status hidden';clearNotice();step(1);};
$('connect').onclick=()=>{$('token').value=state.key;$('authError').textContent='';$('authDialog').showModal();};$('cancelAuth').onclick=()=>$('authDialog').close();$('authForm').onsubmit=e=>{e.preventDefault();state.key=$('token').value.trim();sessionStorage.setItem('fairytale-gemini-key',state.key);$('authDialog').close();notice('Gemini API 키를 현재 탭에 저장했습니다.');};if(!state.key)notice('처음 사용할 때 상단의 Gemini API 키 설정을 눌러 주세요. 영상은 서버에 업로드하지 않습니다.');else notice('무료형 스튜디오입니다. 영상 파일은 이 기기에서만 처리합니다.');}
init();
