'use strict';
/* All media processing stays in this browser. Gemini receives only the narration text. */
window.FairyNarration=(()=>{
const VOICES={
 warmFemale:['Kore','Speak in warm, gentle, comforting Korean, like a caring bedtime storyteller.'],
 calmMale:['Charon','Speak in a calm, reassuring Korean male storyteller style.'],
 storyteller:['Puck','Speak in a cheerful and expressive Korean fairy-tale storyteller style, never shouting.'],
 grandma:['Aoede','Speak in Korean like a kind elderly grandmother reading a bedtime fairy tale, gentle and affectionate, with a mature unhurried delivery.'],
 grandpa:['Charon','Speak in Korean like a kind elderly grandfather telling a bedtime fairy tale, warm, mature, gentle and reassuring.']
};
function decode64(str){const raw=atob(str),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out;}
function wav(pcm,rate=24000){const buf=new ArrayBuffer(44+pcm.length),d=new DataView(buf);const ascii=(off,t)=>{for(let i=0;i<t.length;i++)d.setUint8(off+i,t.charCodeAt(i));};ascii(0,'RIFF');d.setUint32(4,36+pcm.length,true);ascii(8,'WAVE');ascii(12,'fmt ');d.setUint32(16,16,true);d.setUint16(20,1,true);d.setUint16(22,1,true);d.setUint32(24,rate,true);d.setUint32(28,rate*2,true);d.setUint16(32,2,true);d.setUint16(34,16,true);ascii(36,'data');d.setUint32(40,pcm.length,true);new Uint8Array(buf,44).set(pcm);return new Uint8Array(buf);}
async function speech(key,text,voice,pace){const [name,style]=VOICES[voice]||VOICES.warmFemale;const speed={slow:'Slow, with gentle pauses.',normal:'Natural and unhurried.',fast:'Lively but clear.'}[pace]||'Natural and unhurried.';const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-tts-preview:generateContent',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents:[{parts:[{text:'Read aloud ONLY the Korean narration below. '+style+' '+speed+' Do not say the instructions.\n\n'+text}]}],generationConfig:{responseModalities:['AUDIO'],speechConfig:{voiceConfig:{prebuiltVoiceConfig:{voiceName:name}}}}})});const data=await r.json().catch(()=>({}));if(!r.ok)throw Error('Gemini 음성 생성 실패: '+(data.error?.message||'HTTP '+r.status));const part=data.candidates?.flatMap(c=>c.content?.parts||[]).find(p=>p.inlineData?.data);if(!part)throw Error('Gemini가 음성 데이터를 반환하지 않았습니다. TTS 모델 사용 권한이나 사용량을 확인하세요.');const pcm=decode64(part.inlineData.data);const rate=Number(part.inlineData.mimeType?.match(/rate=(\d+)/)?.[1])||24000;return {data:wav(pcm,rate),duration:pcm.length/(rate*2)};}
function caption(text){const canvas=document.createElement('canvas');canvas.width=720;canvas.height=210;const ctx=canvas.getContext('2d');ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='bold 42px sans-serif';const words=Array.from(text.trim());const lines=[];let line='';for(const c of words){if(ctx.measureText(line+c).width>645&&line){lines.push(line);line=c;}else line+=c;}if(line)lines.push(line);const shown=lines.slice(0,3);ctx.fillStyle='rgba(0,0,0,.65)';const h=shown.length*55+28;ctx.beginPath();ctx.roundRect(10,210-h,700,h,18);ctx.fill();shown.forEach((l,i)=>{const y=210-h+36+i*55;ctx.lineWidth=5;ctx.strokeStyle='rgba(0,0,0,.9)';ctx.strokeText(l,360,y);ctx.fillStyle=i===0?'#ffe071':'#ffffff';ctx.fillText(l,360,y);});return new Promise((resolve,reject)=>canvas.toBlob(async blob=>blob?resolve(new Uint8Array(await blob.arrayBuffer())):reject(Error('자막 이미지 생성 실패')),'image/png'));}
function videoDuration(file){return new Promise((resolve,reject)=>{const v=document.createElement('video'),u=URL.createObjectURL(file);v.preload='metadata';v.onloadedmetadata=()=>{const d=v.duration;URL.revokeObjectURL(u);resolve(Number.isFinite(d)&&d>0?d:8);};v.onerror=()=>{URL.revokeObjectURL(u);reject(Error('영상 길이를 읽지 못했습니다: '+file.name));};v.src=u;});}
async function render({project,files,key,voice,pace,subtitles,bgVolume,box,loadFFmpeg,onDone}){if(!key)throw Error('Gemini API 키를 먼저 입력해 주세요.');await loadFFmpeg();const ff=new window.FFmpegWASM.FFmpeg();let stage='엔진 초기화';try{const base=new URL('ffmpeg/',document.baseURI);await ff.load({coreURL:new URL('ffmpeg-core.js',base).href,wasmURL:new URL('ffmpeg-core.wasm',base).href,classWorkerURL:new URL('worker.js',base).href});ff.on('log',({message})=>{if(/time=/.test(message))box.textContent='영상 합성 중… '+message.slice(-85);});const names=[];for(let i=0;i<project.cuts;i++){const scene=project.scenes[i],file=files.get(i);if(!file)throw Error('컷 '+(i+1)+'의 MP4가 없습니다.');if(!scene.narration?.trim())throw Error('컷 '+(i+1)+'의 한국어 나레이션 대본이 비어 있습니다. 2단계에서 입력해 주세요.');stage='컷 '+(i+1)+' 나레이션 생성';box.textContent='🎙️ '+(i+1)+' / '+project.cuts+'컷 한국어 나레이션 생성 중…';const audio=await speech(key,scene.narration,voice,pace);stage='컷 '+(i+1)+' 영상 처리';box.textContent='🎬 '+(i+1)+' / '+project.cuts+'컷 목소리·자막 합성 중…';const video='video'+i+'.mp4',wave='voice'+i+'.wav',png='caption'+i+'.png',output='scene'+i+'.mp4';await ff.writeFile(video,new Uint8Array(await file.arrayBuffer()));await ff.writeFile(wave,audio.data);const vd=await videoDuration(file);const duration=Math.max(vd,audio.duration+0.45);const extra=Math.max(0,duration-vd);const args=['-i',video,'-i',wave];let filter='[0:v]tpad=stop_mode=clone:stop_duration='+extra.toFixed(3)+'[held];';let mapped='[held]';if(subtitles){await ff.writeFile(png,await caption(scene.narration));args.push('-i',png);filter+='[held][2:v]overlay=x=(main_w-overlay_w)/2:y=main_h-overlay_h-45:shortest=1[v];';mapped='[v]';}
const sound='[0:a]volume='+Number(bgVolume).toFixed(2)+',apad[bg];[1:a]apad[nar];[bg][nar]amix=inputs=2:duration=first:dropout_transition=0[a]';const silent='[1:a]apad[a]';const common=['-map',mapped,'-map','[a]','-t',duration.toFixed(3),'-c:v','libx264','-preset','ultrafast','-crf','26','-pix_fmt','yuv420p','-c:a','aac','-b:a','128k','-movflags','+faststart',output];let rc=await ff.exec([...args,'-filter_complex',filter+sound,...common]);if(rc!==0){box.textContent='컷 '+(i+1)+'의 원본 배경음이 없어 나레이션만으로 다시 합성 중…';rc=await ff.exec([...args,'-filter_complex',filter+silent,...common]);}if(rc!==0)throw Error('컷 '+(i+1)+'의 영상 인코딩에 실패했습니다. 기기 메모리 또는 영상 형식을 확인해 주세요.');names.push(output);await ff.deleteFile(video);await ff.deleteFile(wave);if(subtitles)await ff.deleteFile(png);}
stage='최종 MP4 병합';box.textContent='모든 컷을 하나의 MP4로 합치는 중…';await ff.writeFile('list.txt',new TextEncoder().encode(names.map(n=>"file '"+n+"'").join('\n')));const rc=await ff.exec(['-f','concat','-safe','0','-i','list.txt','-c','copy','-movflags','+faststart','final.mp4']);if(rc!==0)throw Error('최종 영상 병합에 실패했습니다.');const out=await ff.readFile('final.mp4');if(out.byteLength<1000)throw Error('완성 MP4가 비어 있습니다.');onDone(new Blob([out],{type:'video/mp4'}));}catch(e){throw Error('['+stage+'] '+(e?.message||String(e)));}finally{ff.terminate();}}
return {render,VOICES,wav,caption};
})();
